export type AiTaskType =
  | 'summarize-email'
  | 'summarize-thread'
  | 'help-me-write'
  | 'improve-writing'
  | 'make-professional'
  | 'make-friendly'
  | 'make-shorter'
  | 'make-longer'
  | 'fix-grammar'
  | 'suggest-reply'
  | 'extract-action-items'
  | 'extract-dates'
  | 'extract-key-info';

export interface AiResponse {
  task: AiTaskType;
  title: string;
  result: string;
  suggestedReplies?: string[];
  actionItems?: string[];
  extractedDates?: { date: string; context: string }[];
  keyPoints?: string[];
}

/**
 * Intelligent AI Email Assistant service with mock processing and extensible architecture
 * for direct Gemini API integration.
 */
export async function executeAiTask(
  task: AiTaskType,
  context: {
    subject?: string;
    body?: string;
    sender?: string;
    draftText?: string;
    userPrompt?: string;
  }
): Promise<AiResponse> {
  // Simulate natural AI thinking latency (400ms - 800ms)
  await new Promise((resolve) => setTimeout(resolve, 600));

  const text = context.draftText || context.body || '';
  const subject = context.subject || 'Email';
  const sender = context.sender || 'Sender';

  switch (task) {
    case 'summarize-email': {
      return {
        task,
        title: 'Executive Summary',
        result: `Key takeaway: ${sender} is sharing updates regarding "${subject}". The primary focus is finalizing specifications, confirming deadlines, and coordinating follow-up steps.`,
        keyPoints: [
          `Sender: ${sender}`,
          `Core topic: ${subject}`,
          `Review needed: Needs feedback or action on discussed items`,
          `Urgency: Medium / High based on upcoming schedule`
        ]
      };
    }

    case 'summarize-thread': {
      return {
        task,
        title: 'Conversation Thread Summary',
        result: `This discussion spans multiple exchanges between ${sender} and team members regarding ${subject}. The conversation moved from initial specification sharing to agreement on calendar slots and design feedback.`,
        keyPoints: [
          `Original proposal delivered with attachment assets`,
          `Feedback acknowledged with enthusiasm`,
          `Consensus reached to hold a sync meeting this afternoon at 3:30 PM`
        ]
      };
    }

    case 'extract-action-items': {
      return {
        task,
        title: 'Extracted Action Items',
        result: 'The following tasks were identified in this message:',
        actionItems: [
          'Review attached spec sheet and contrast elevation tokens',
          'Confirm availability for the 10-minute sync at 3:30 PM',
          'Test swipe gesture velocity friction on real touch hardware',
          'Share final sign-off before end of week release'
        ]
      };
    }

    case 'extract-dates': {
      return {
        task,
        title: 'Dates & Deadlines Detected',
        result: 'Identified upcoming events and temporal markers:',
        extractedDates: [
          { date: 'Today, 3:30 PM', context: 'Design tokens review sync call' },
          { date: 'Tomorrow morning', context: 'Stripe payout expected deposit arrival' },
          { date: 'Saturday, 8:30 AM', context: 'Mt. Tam Steep Ravine trail run & Siren Canteen lunch' },
          { date: 'October 14, 11:30 AM', context: 'Flight UA 875 SFO -> HND departure' }
        ]
      };
    }

    case 'extract-key-info': {
      return {
        task,
        title: 'Key Insights & Entities',
        result: 'Highlights extracted from the email content:',
        keyPoints: [
          `Entity: ${sender}`,
          'Key parameters: Modern Material 3 dark surface elevations',
          'Safety status: Verified SPF/DKIM authenticated domain',
          'Next steps: Synchronize feedback with design engineering'
        ]
      };
    }

    case 'suggest-reply': {
      return {
        task,
        title: 'Smart Reply Suggestions',
        result: 'Choose one of the generated quick responses or insert into your draft:',
        suggestedReplies: [
          `Thanks ${sender.split(' ')[0]}, this looks great! 3:30 PM works perfectly for me.`,
          `Received! I will review the spec tokens and send over detailed notes shortly.`,
          `Appreciate the update. Let's sync this afternoon and review the prototype live.`
        ]
      };
    }

    case 'help-me-write': {
      const prompt = context.userPrompt || 'Follow up on the proposal';
      return {
        task,
        title: 'Draft Generated by MailFlow AI',
        result: `Hi ${sender.split(' ')[0]},

Thank you for reaching out regarding ${subject.replace(/^(re:|fwd:)\s*/i, '')}.

I reviewed the points you outlined and wanted to follow up with our status. Everything is on track and looking great. Let's touch base soon to finalize the next deliverables.

Best regards,
Alex Morgan`
      };
    }

    case 'make-professional': {
      return {
        task,
        title: 'Polished Professional Tone',
        result: text
          ? text
              .replace(/hey/gi, 'Hello')
              .replace(/thanks/gi, 'Thank you for your assistance')
              .replace(/cool|awesome/gi, 'excellent')
              .replace(/let me know/gi, 'please inform me at your earliest convenience')
          : `Dear colleagues,\n\nI am writing to provide a formal update on our recent milestones. Please review the attached deliverables at your earliest convenience.`
      };
    }

    case 'make-friendly': {
      return {
        task,
        title: 'Warm & Friendly Tone',
        result: `Hey there! 😊 Hope you are having a wonderful week! Just wanted to quickly circle back on ${subject.toLowerCase()} and say thanks for all your help on this. Looking forward to catching up soon!`
      };
    }

    case 'make-shorter': {
      return {
        task,
        title: 'Concise Bullet Version',
        result: `Summary update on ${subject}:
• Reviewed latest tokens and elevated cards
• Looks solid for mobile and desktop testing
• Sync meeting scheduled for 3:30 PM today`
      };
    }

    case 'make-longer': {
      return {
        task,
        title: 'Expanded Detailed Draft',
        result: `Hi ${sender.split(' ')[0]},

Thank you for the comprehensive update regarding ${subject}.

I wanted to take a moment to elaborate on a few pertinent areas:
First, the visual hierarchy and Material 3 elevations provide an immediate boost to readability on both mobile OLED displays and desktop panels. Second, the tactile swipe responsiveness feels fluid and intuitive.

I look forward to discussing our next steps during our upcoming sync. Please feel free to loop in any additional team members who should be present.

Warm regards,
Alex Morgan`
      };
    }

    case 'fix-grammar': {
      return {
        task,
        title: 'Grammar & Clarity Corrected',
        result: (text || 'Please review the updated specification files. Everything is functioning correctly.')
          .trim()
          .replace(/\s+/g, ' ')
      };
    }

    case 'improve-writing':
    default: {
      return {
        task,
        title: 'Writing Enhanced',
        result: `Thank you for sharing the latest updates. I have reviewed the core elements of ${subject} and believe we are aligned on the direction. Let me know if you would like to make any adjustments before we proceed.`
      };
    }
  }
}
